/*
  Author: 	Cameron Palk
  Date:   	September 2016
  Version: 	1.0.0
*/

'use strict';

const
  express    = require('express'),
  bodyParser = require('body-parser'),
  config     = require('config');



// Express App
var app = express();



// App middleware
app.use(bodyParser.json());
app.use(express.static('public'));



/*
  APP_SECRET:         On App Dashoard https://developers.facebook.com/apps/1762589327347412/dashboard/
  VALIDATION_TOKEN:   Generated by me, used in Webhook validation
  PAGE_ACCESS_TOKEN:  On App Dashboard, used to connect the Facebook page
  SERVER_URL:         URL where the app is running
*/
const
  APP_SECRET        = process.env.MESSENGER_APP_SECRET ||
                      config.get('appSecret'),
  VALIDATION_TOKEN  = process.env.MESSENGER_VALIDATION_TOKEN ||
                      config.get('validationToken'),
  PAGE_ACCESS_TOKEN = process.env.MESSENGER_PAGE_ACCESS_TOKEN ||
                      config.get('pageAccessToken'),
  SERVER_URL        = process.env.SERVER_URL ||
                      config.get('serverURL');


// Ensure these required values have been found
if (!(APP_SECRET && VALIDATION_TOKEN && PAGE_ACCESS_TOKEN && SERVER_URL)) {
  console.err("Missing config values");
  process.exit(1);
}
else {
  console.log("Located app values:");
  console.log("APP_SECRET:", APP_SECRET,
              "\nVALIDATION_TOKEN:", VALIDATION_TOKEN,
              "\nPAGE_ACCESS_TOKEN:", PAGE_ACCESS_TOKEN,
              "\nSERVER_URL:", SERVER_URL);
}
